---
version: "3"

services:
  traefik:
    image: traefik:v2.4
    restart: always
    depends_on:
      - foo
      - bar
    ports:
      - 80:80
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic.yml:/etc/traefik/dynamic/dynamic.yml:ro

  foo:
    image: traefik/whoami:v1.8.1
    restart: always
    hostname: foo

  bar:
    image: traefik/whoami:v1.8.1
    restart: always
    hostname: bar
