---
# Enable the Traefik API (api@internal service)
api: {}

# Enable access logging to stdout
accessLog: {}

providers:
  # Use the dynamic.yml file as dynamic configuration provider
  file:
    directory: /etc/traefik/dynamic
