---
http:
  routers:
    dashboard:
      entryPoints: [websecure]
      rule: Host(`dashboard.example.com`)
      middlewares: [auth-dashboard]
      service: api@internal
    main:
      entryPoints: [websecure]
      rule: Host(`example.com`)
      middlewares: [redirect-www]
      service: noop@internal

  middlewares:
    auth-dashboard:
      digestAuth:
        removeHeader: true
        users: [admin:traefik:817374111f31cc282162486425ee5e9e]
    redirect-www:
      redirectRegex:
        regex: "^https://example.com/(.*)"
        replacement: "https://www.example.com/${1}"
        permanent: true

tls:
  certificates:
    # Traefik automatically assigns the certificate to the corresponding routers
    # based on the SSL "CommonName" attribute
    - certFile: /etc/traefik/server.crt
      keyFile: /etc/traefik/server.key
