---
http:
  routers:
    dashboard:
      entryPoints: [websecure]
      rule: Host(`dashboard.example.com`)
      middlewares: [auth-dashboard]
      service: api@internal

  middlewares:
    auth-dashboard:
      digestAuth:
        removeHeader: true
        users: [admin:traefik:817374111f31cc282162486425ee5e9e]
