---
http:
  routers:
    dashboard:
      rule: Host(`dashboard.example.com`)
      service: api@internal
      entryPoints: [websecure]
      middlewares:
        - auth-dashboard

  middlewares:
    auth-dashboard:
      digestAuth:
        removeHeader: true
        users:
          - admin:traefik:817374111f31cc282162486425ee5e9e
