---
metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Disable modules config reloading
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      # Enable reading labels from containers
      hints.enabled: true
      # Disable sending container metrics into Elastic by default. In this way,
      # only metrics from containers with the "co.elastic.metrics/enabled" label
      # set to "true" will be sent to Elastic
      hints.default_config.enabled: false

# The following section is to monitor all Docker containers
metricbeat.modules:
  - module: docker
    hosts: [unix:///var/run/docker.sock]
    metricsets:
      - container
      - cpu
      - diskio
      - healthcheck
      - info
      # - image
      - memory
      - network
    period: 10s
    enabled: true

output.elasticsearch:
  hosts: elasticsearch:9200
  username: ""
  password: ""
